services:
  nextjs-skeleton:
    build: .
    container_name: nextjs-skeleton
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./next.config.ts:/app/next.config.ts
    environment:
      - WATCHPACK_POLLING=true
    command: npm run dev
    restart: unless-stopped
